spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create